### ISSUE TITLE
Active Evaluations - please revert change... exclude REVIEWED status from being counted as Completed.

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#345]
**DESCRIPTION**

- [ ] Please revert change and exclude REVIEWED status from being counted as Completed.
- [ ] So it should only count SUBMITTED / [ OPEN + ONGOING ] since these are the only evaluations shown in the evaluation list.

![Image](https://github.com/nerubia/kh360-react/assets/1640285/de727cf3-163b-4e2a-9bb0-22b1756888cb)

**Comment by emmaacha** [comment]
PR: [#318](https://github.com/nerubia/kh360-nodejs/pull/318)

**Comment by sheilaramas** [comment]
Not yet in Beta

**Comment by emmaacha** [comment]
Added the wrong change, fixed here: PR #323

**Comment by sheilaramas** [comment]
Still wrong. Refer to screen recording for reference.



https://github.com/nerubia/kh360-react/assets/1640285/889b8aeb-28e0-43a3-8c7f-54e4a68736f5

Here, 9 is displayed as total number of evaluations. But it should be 8 only (to exclude Reviewed status)
DB Screenshot below.




![Image](https://github.com/nerubia/kh360-react/assets/1640285/b1e13322-154b-45bf-9282-dd8127c79213)

**Comment by emmaacha** [comment]
[#345](https://github.com/nerubia/kh360-nodejs/pull/345)

**Comment by sheilaramas** [comment]
👎 lol


![Image](https://github.com/nerubia/kh360-react/assets/1640285/609342c3-23c2-4aee-80b6-567abab8bb9a)



![Image](https://github.com/nerubia/kh360-react/assets/1640285/40e25135-dc94-4cf9-be1d-efd426654bd6)



It should be 1 of 8. Not 1 of 7 Evaluations Submitted

**Comment by emmaacha** [comment]
PR: [#363](https://github.com/nerubia/kh360-nodejs/pull/363)

**Comment by sheilaramas** [comment]
Yaay! ok verified in Beta!

**Comment by jasonoperez23** [comment]
Hi,

Unable to test in Beta, as per @sheilaramas there is no way in the front end to change status to REVIEWED.

Thanks
